require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.autopairs"
require "user.lualine"
require "user.nvim-tree"
require "user.telescope"
require "user.project"
require "user.treesitter"
-- require "user.indentline"
require "user.cmp"
require "user.lsp"
require "user.gitsigns"
require "user.whichkey"
require "user.whitespace"
require "user.autocommands"
require "user.alpha"
